# Specifies the layers of a fully connected neural network model
# Using MNIST data

model-type: fully-connected
input-size: 784  # 28 * 28 pixels
number-of-layers: 3
layers:
  - layer:
      type: linear
      neurons: 500
      activation: relu
      dropout: none
  - layer:
      type: linear
      neurons: 256
      activation: sigmoid
      dropout: none
  - layer:
      type: linear
      neurons: 10
      activation: relu
      dropout: none
  # output layer
  #- layer:
  #    type: output
  #    input: 10
  #    activation: softmax
  #    dropout: none
