# Specifies the layers of a fully connected neural network model
# Using MNIST data
model_type: fully-connected
input_size: 784  # 28 * 28 pixels
number_of_layers: 3 # Todo: Remove. Redundant
layers:
  - layer:
      type: linear
      neurons: 500
      activation: relu
      dropout: none
  - layer:
      type: linear
      neurons: 256
      activation: sigmoid
      dropout: none
  - layer:
      type: linear
      neurons: 10
      activation: relu
      dropout: none
# Refactor Hyperparameters?
objective: mseloss
optimization: SGD
# output layer
#- layer:
#    type: output
#    input: 10
#    activation: softmax
#    dropout: none
