model_type: fully-connected
input_size: 2
number_of_layers: 1
layers:
  - layer:
      type: linear
      neurons: 1
      activation: relu
      dropout: None

# The output of each layer is implicit; set from inputs of next layer
objective: mseloss
optimization: SGD
#  learning-rate: 0.01
#  momentum: 0.5
