# 2 Layer fully connected model
model_type: fully-connected
input_size: 2
layers:
  - layer:
      type: linear
      neurons: 1
      activation: relu
      dropout: None
  - layer:
      type: linear
      neurons: 1
      activation: relu
      dropout: None
hyperparameters:
# The output of each layer is implicit; set from inputs of next layer
  objective: mseloss
  learning-rate: 0.01
  momentum: 0.5
  optimization: SGD


